trailingComma: "es5"
semi: false
singleQuote: false
jsxSingleQuote: false
tabWidth: 4
useTabs: false
endOfLine: lf
printWidth: 160
overrides:
  - files: "*.json"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
